# Generated by Django 5.0.3 on 2024-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
